#!/usr/bin/env python2.7

import logging, sys

from common.sx4itconf import Sx4itConf
from controller.server import Server

if __name__ == '__main__':
    #import argparse
    if Sx4itConf.opts['controller_debug'] == True:
        logging.basicConfig(level=logging.DEBUG)
    #parser = argparse.ArgumentParser(description='Controller.')
    #parser.add_argument('port', type=int, nargs=1,
    #                    help='The port on wich to bind')
    #opts = parser.parse_args()
    try:
        Server.instance().configure(sys.argv[1], Sx4itConf.opts)
        Server.instance().run()
    except KeyboardInterrupt:
        logging.debug("Ending controller" + sys.argv[1])
